title: Linaro
url: https://www.linaro.org
baseurl: ""
description: |-
  Linaro is a collaborative engineering organization consolidating and optimizing open source software and tools for the Arm architecture.
destination: _site
permalink: /:categories/:title/
theme: linaro-jekyll-theme
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
safe: false
livereload_ignore:
  - .asset_pipeline/assets/js/*.js
  - .asset_pipeline/assets/js/*.js.gz
exclude:
  - Gemfile
  - Gemfile.lock
  - .asset_pipeline
  - build-site.sh
  - check-links.sh
  - CODEOWNERS
  - README.md
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - staging.linaro.org
  - production.linaro.org
# Breadcrumb banner image
breadcrumb_banner: /assets/images/content/code_banner.jpg
# Toggle the animated navbar dropdown feature
# Navbar dropdowns will open on hover
hover_nav_dropdowns: true
# Set the class used to animate dropdowns e.g. fade-up / fade-down
nav_dropdowns_animation_class: fade-down
# The bootstrap breakpoint at which the navbars will expand
nav_expand_breakpoint: xl
sass:
  style: compressed
  load_paths:
    - assets/css
  sourcemap: "never"
plugins:
  - japr
  - jekyll_picture_tag
  - jekyll-tidy
collections:
  services:
    output: true
  themes:
    output: true
  authors:
    output: true
    permalink: /author/:name/
  hub:
    output: true
    permalink: /learning-hub/:name/
  woa:
    output: true
    permalink: /windows-on-arm/:name/
  whitepapers:
    output: true
    permalink: /whitepapers/:name/
liquid:
  error_mode: strict
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
  - scope:
      path: "_pages"
    values:
      layout: flow
  - scope:
      type: posts
      path: "_posts"
    values:
      layout: post
      is_post: true
      tags_enabled: true
      comments: false
      image: /assets/images/content/code_banner.jpg
      strap_image: /assets/images/content/code_banner.jpg
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
      sitemap: false
      image: /assets/images/social-media-image.png
  - scope:
      path: ""
      type: "hub"
    values:
      layout: hub
      css_bundle: learning-hub
      image: /assets/images/social-media-image.png
  - scope:
      type: "services"
    values:
      layout: flow
      css_bundle: services
      js-package: services
      image: /assets/images/content/LinaroDSVertical.png
  - scope:
      type: "themes"
    values:
      layout: flow
      css_bundle: themes
      js-package: themes
      image: /assets/images/content/LinaroDSVertical.png
  - scope:
      type: "woa"
    values:
      layout: flow
      css_bundle: woa
      js-package: about
      image: /assets/images/content/iStock-667012914_sm.jpg
  - scope:
      path: "_posts/events"
    values:
      layout: event
      comments: false
      tags_enabled: false
      author: linaro
      permalink: /events/:title/
      categories: ["Events"]
  - scope:
      path: "_posts/events/resources"
    values:
      layout: resource-post
      comments: false
      tags_enabled: false
      author: linaro
      permalink: /events/:title/
      published: false
      categories: ["event_resources"]
  - scope:
      path: "_posts/awards"
    values:
      author: linaro
      tags_enabled: false
      permalink: "/awards/5-years/:title/"
      comments: false
  - scope:
      type: "whitepapers"
    values:
      layout: whitepaper
      css_bundle: whitepapers
  - scope:
      path: "assets/**/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "admin"
    values:
      sitemap: false
  - scope:
      path: app
    values:
      sitemap: false
  - scope:
      path: remote
    values:
      sitemap: false
  - scope:
      path: "_pages/projects/"
    values:
      sitemap: false
  # - scope:
  #     path: "/sitemap.xml"
  #   values:
  #     redirect_from: /sitemap/
include: ["_pages", "generated"]
# ----------- THEME / WEBSITE CONFIG ---------------------
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Email
email: contact@linaro.org
# Company Address
address:
  - Harston Mill
  - Royston Rd, Harston
  - Cambridge, United Kingdom
  - CB22 7GG
# Support for http2 preload features
http2_resources:
  - rel: preload
    as: font
    type: font/woff2
    crossorigin: true
    href: /assets/fonts/lato/Lato-regular.woff2
google_analytics:
  enabled: true
  code: GTM-XXXXX
  cookies:
    necessary:
      - name: cookieControl
        description: >
          This is used to control the display of the preferences pop up. Without this, we wouldn't know if you've clicked Accept!
      - name: cookieControlPrefs
        description: >
          This is used to store your cookie preferences. Without this we wouldn't know which cookies you want!
    marketing:
      - name: _ga
        description: >
          2 years - Used to distinguish users.
      - name: _gid
        description: >
          24 hours - Used to distinguish users.
      - name: _gat
        description: >
          1 minute - Used to throttle request rate.
      - name: HotJar
        description: >
          We use hotjar to help us understand how we can improve our end-user experience. For a list of cookies HotJar uses please see [https://help.hotjar.com/hc/en-us/articles/115011789248-Hotjar-Cookies#cookies-set-by-the-hotjar-script](https://help.hotjar.com/hc/en-us/articles/115011789248-Hotjar-Cookies#cookies-set-by-the-hotjar-script)
# Set the site-wide default social media share image.
social_media_share_image: /assets/images/social-media-image.png
# Set the default favicon
favicon: /assets/images/favicon.png
# Site Name - your brand name
name: Jumbo Jekyll Theme
# The blog filler element
blog_filler_element: blog/blog_filler_element.html
# Placeholder avatar
avatar_placeholder: /assets/images/avatar-placeholder.jpg
# Blog Post Image Placeholder
post_placeholder: /assets/images/content/linaro-logo.png
# Social Media Links
social_media_channels:
  github:
    url: https://github.com/Linaro
  linkedin:
    url: https://www.linkedin.com/company/1026961
  facebook:
    url: http://facebook.com/LinaroOrg
  youtube:
    url: https://www.youtube.com/linaroorg
  twitter:
    url: https://twitter.com/linaroorg
  instagram:
    url: https://instagram.com/linaroorg
# Disqus Comments Setup
disqus:
  enabled: false
  shortname: Linaro
# Edit on GitHub Settings
edit-on-github:
  enabled: true
  repo: https://www.github.com/Linaro/website
# Breadcrumb schema
breadcrumb_schema: true
# Shema.org settings used in the schema.html include.
schema:
  "@context": "https://schema.org"
  "@type": "Organization"
  "name": "Linaro"
  "url": "https://www.linaro.org"
  "email": "contact@linaro.org"
  "logo": "https://www.linaro.org/assets/images/content/linaro-logo.png"
  "contactPoint":
    "@type": "ContactPoint"
    "telephone": "01223 400060"
    "contactType": "customer service"
    "availableLanguage": "en"
  "sameAs": "https://www.linaro.org"
# FESS search label
search_label: Linaro
keep_files: ["../generated"]
# ----------- JEKYLL PLUGINS ---------------------
# -------- jekyll-tidy --------
jekyll_tidy:
  # Toggle compression of HTML
  compress_html: true
  # JS Path added to exclude to stop errors.
  exclude: ["assets/**/*.js", "robots.txt", "admin/config.yml"]
# -------- jekyll_relative_links --------
jekyll_relative_links:
  process_all_collections: true
  verbose: 1
relative_links:
  enabled: true
  collections: false
# -------- jekyll_relative_links --------
readme_index:
  enabled: true
  remove_originals: false
# -------- jekyll_picture_tag --------
picture:
  nomarkdown: false
  suppress_warnings: true
  source: ""
  output: "../generated"
  relative_url: true
# -------- japr --------
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets/js
  gzip: true
# Jekyll-polyglot
i18n_enabled: true
languages: ["en", "ch"]
default_lang: "en"
exclude_from_localization:
  [
    "admin",
    "app",
    "assets",
    "css",
    "generated",
    "images",
    "javascript",
    "public",
    "remote",
    "robots.txt",
    "favicon.ico",
  ]
parallel_localization: false
