# Website title - used in the <title> tag of the <head> section of the website.
title: Linaro
# Description of the website used in the Meta Description.
description: > # this means to ignore newlines until "baseurl:"
  Linaro is a collaborative engineering organization consolidating and optimizing open source software and tools for the Arm architecture.
# Destination of the Jekyll site upon build of site.
destination: staging.linaro.org
# Include the Linaro Jekyll Theme
theme: jumbo-jekyll-theme
# Permalink for the blog posts of the Jekyll website.
permalink: /:categories/:title/
# Syntax highlighter for 96boards blog
highlighter: rouge
# Markdown version
markdown: kramdown
# production status for robots.txt and files alike.
production: false
kramdown:
  input: GFM
  syntax_highlighter: rouge # Syntax highlighter for Kramdown.
# Encoding of the files being included in the Jekyll Build.
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Search label setting for site search with e.g. search/?fields.label=96Boards
search-label: Linaro

# Disqus Comments settings.
disqus: true
disqus_shortname: 'Linaro'

# This is the url that is used when your site is built for canonicals etc.
url: "https://staging.linaro.org"
# url: "https://www.site-test.linaro.org"

# Make sure that Liquid errors stop the build
liquid:
    error_mode: strict

# Shema.org Setup -> used in the schema.html include.
schema:
    organisation:
        name: Linaro
        url: https://www.linaro.org
        sameAs:
            - https://twitter.com/linaroorg
            - https://www.facebook.com/LinaroOrg
            - https://www.linkedin.com/company/1026961/
            - https://plus.google.com/+LinaroOnAir
            - https://github.com/Linaro
            - https://www.slideshare.net/linaroorg
        address:
            street: Harston Mill, Royston Rd 
            town: Harston 
            county: Cambridge 
            post_code: CB22 7GG
            country_code: UK 
# Files that should be excluded from the Jekyll build.
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .git
  - .asset-cache
  - _site
  # - _posts

# Google Tag mangager site wide setting - for deployment of site to China.
google-tag-manager: true

# Social Configuration for the Jekyll SEO plugin.
social:
  name: Linaro
  links:
    - https://twitter.com/linaroorg
    - https://www.facebook.com/LinaroOrg
    - https://www.linkedin.com/company/1026961/
    - https://plus.google.com/+LinaroOnAir
    - https://github.com/Linaro
    - https://www.slideshare.net/linaroorg
twitter:
    username: linaroorg

defaults:
  - scope:
        path: ""
        type: "posts"
    values:
        layout: post
        comments: true
  - scope:
        path: ""
        type: "company"
    values:
        layout: container-breadcrumb
  - scope:
        path: ""
        type: "authors"
    values:
        layout: author
  - scope:
        path: ""
        type: "groups"
    values:
        layout: work-layout
  - scope:
        path: ""
        type: "core"
    values:
        layout: work-layout
  - scope:
        path: ""
        type: "projects"
    values:
        layout: work-layout
  - scope:
        path: ""
        type: "services"
    values:
        layout: developer-services
  - scope:
        path: ""
        type: "initiatives"
    values:
        layout: work-layout
  - scope:
        path: ""
        type: "incubators"
    values:
        layout: work-layout
  - scope:
        path: ""
        type: "sig"
    values:
        layout: work-layout
  - scope:
        path: "/sitemap.xml"
    values:
        redirect_from: /sitemap/
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
      
# Gems that should be included in the Jekyll builld of this site.
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-readme-index
  - bootstrap-sass
  - uglifier
  - jekyll-assets
  - jekyll-tidy
  - jekyll-redirect-from
  - autoprefixer-rails
  - jekyll-paginate-v2
    
# Compress the html and beau2tify it.
jekyll_tidy: # Compress the html and beautify it.
    compress_html: true
    exclude: [robots.txt] # Exclude the robots.txt file from removal of whitespace

# Jekyll Assets plugin - set js and css to true so it compresses on jekyll build
assets:
  compress:
        js: true
  autoprefixer:
      browsers: ["last 2 versions","> 5%","IE 9"]
  sources:
    - assets/js/
    - assets/js/vendor/
    - assets/js/app/
    - assets/images
    - assets/images/members
    - assets/images/people
    - assets/images/content
    - assets/images/blog
    - assets/css/

# Sass configuration - compressed and sass_dir of the root Jekyll assets folder.
sass:
    style: compressed
    load_paths:
        - assets/css
#paginate_path: /:categories/:num/

# Jekyll Pagination V2 Configuration
pagination:
    permalink: '/:num/'
    enabled: true
    per_page: 10
    trail:
        before: 2
        after: 2
    sort_reverse: true
    sort_field: 'date'

# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false

# MiniMagick magic on the images stored in asset/images 
# All images will have a thumbnail (100x100), medium(300x300) and large(500x500)
# image created and stored in /assets/images/thumbnails/, /assets/images/medium/
# and /assets/images/large/ respectively.

mini_magick:
    # Blog Image Presets
    blog_thumbnail:
        source: assets/images/blog
        destination: assets/images/thumbnails/blog
        resize: "100x100"
        thumbnail: "100x100>"
        gravity: "Center"
        extent: "100x100"
    blog_medium:
        source: assets/images/blog
        destination: assets/images/medium/blog
        resize: "300x300"
        thumbnail: "300x300>"
        gravity: "Center"
        extent: "300x300"
    blog_large:
        source: assets/images/blog
        destination: assets/images/large/blog
        resize: "500x500"
        thumbnail: "500x500>"
        gravity: "Center"
        extent: "500x500"
    # Content Image Presets
    content_thumbnail:
        source: assets/images/content
        destination: assets/images/thumbnails/content
        resize: "100x100"
        thumbnail: "100x100>"
        gravity: "Center"
        extent: "100x100"
    content_medium:
        source: assets/images/content
        destination: assets/images/medium/content
        resize: "300x300"
        thumbnail: "300x300>"
        gravity: "Center"
        extent: "300x300"
    content_large:
        source: assets/images/content
        destination: assets/images/large/content
        resize: "500x500"
        thumbnail: "500x500>"
        gravity: "Center"
        extent: "500x500"
    # Content Image Presets
    members_thumbnail:
        source: assets/images/members
        destination: assets/images/thumbnails/members
        resize: "100x100"
        thumbnail: "100x100>"
        gravity: "Center"
        extent: "100x100"
    members_medium:
        source: assets/images/members
        destination: assets/images/medium/members
        resize: "300x300"
        thumbnail: "300x300>"
        gravity: "Center"
        extent: "300x300"
    members_large:
        source: assets/images/members
        destination: assets/images/large/members
        resize: "500x500"
        thumbnail: "500x500>"
        gravity: "Center"
        extent: "500x500"
    # People Image Presets
    people_thumbnail:
        source: assets/images/people
        destination: assets/images/thumbnails/people
        resize: "100x100"
        thumbnail: "100x100>"
        gravity: "Center"
        extent: "100x100"
    people_medium:
        source: assets/images/people
        destination: assets/images/medium/people
        resize: "300x300"
        thumbnail: "300x300>"
        gravity: "Center"
        extent: "300x300"
    people_large:
        source: assets/images/people
        destination: assets/images/large/people
        resize: "500x500"
        thumbnail: "500x500>"
        gravity: "Center"
        extent: "500x500"
        
using_assets: true

# Jekyll Collections configuration - Projects, Products and Documentation.
collections:
    company:
        output: true
        permalink: /:collection/:name/
    core:
        output: true
        permalink: /:collection/:path/
    projects:
        output: true
        permalink: /:collection/:path/
    initiatives:
        output: true
        permalink: /:collection/:path/
    groups:
        output: true
        permalink: /:collection/:path/
    sig:
        output: true
        permalink: /:collection/:path/
    incubators:
        output: true
    services:
        output: true
        permalink: /:collection/:name/
    authors:
        output: true
        permalink: /author/:name/
