# Website title - used in the <title> tag of the <head> section of the website.
title: Linaro
# Description of the website used in the Meta Description.
description: > # this means to ignore newlines until "baseurl:"
  Linaro is a collaborative engineering organization consolidating and optimizing open source software and tools for the Arm architecture.
# Destination of the Jekyll site upon build of site.
destination: _site
# Include the Linaro Jekyll Theme
theme: jumbo-jekyll-theme
# Permalink for the blog posts of the Jekyll website.
permalink: /:categories/:title/
# Jekyll Responsive Images dir
blog_images_dir: assets/images/blog/
email: contact@linaro.org
# Syntax highlighter for 96boards blog
highlighter: rouge
# Markdown version
markdown: kramdown
# production status for robots.txt and files alike.
production: false
kramdown:
  input: GFM
  syntax_highlighter: rouge # Syntax highlighter for Kramdown.
# Encoding of the files being included in the Jekyll Build.
encoding: utf-8
# Jekyll configuration for running the site in "Safe" mode.
safe: false
# Search label setting for site search with e.g. search/?fields.label=96Boards
search-label: Linaro
# Disqus Comments settings.
disqus: true
disqus_shortname: "Linaro"
# This is the url that is used when your site is built for canonicals etc.
url: "https://www.linaro.org"
# url: "https://www.site-test.linaro.org"

# Make sure that Liquid errors stop the build
liquid:
  error_mode: strict

# Shema.org Setup -> used in the schema.html include.
schema:
  organisation:
    name: Linaro
    url: https://www.linaro.org
    sameAs:
      - https://twitter.com/linaroorg
      - https://www.facebook.com/LinaroOrg
      - https://www.linkedin.com/company/1026961/
      - https://plus.google.com/+LinaroOnAir
      - https://github.com/Linaro
      - https://www.slideshare.net/linaroorg
    address:
      street: Harston Mill, Royston Rd
      town: Harston
      county: Cambridge
      post_code: CB22 7GG
      country_code: UK
# Files that should be excluded from the Jekyll build.
exclude:
  - _site
  - build-site.sh
  - check-links.sh
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - README.md
  - staging.linaro.org
  - production.linaro.org
  # - _posts

# Google Tag mangager site wide setting - for deployment of site to China.
google-tag-manager: true

# Social Configuration for the Jekyll SEO plugin.
social:
  name: Linaro
  links:
    - https://twitter.com/linaroorg
    - https://www.facebook.com/LinaroOrg
    - https://www.linkedin.com/company/1026961/
    - https://plus.google.com/+LinaroOnAir
    - https://github.com/Linaro
    - https://www.slideshare.net/linaroorg
twitter:
  username: linaroorg
# Jekyll Collections configuration - Projects, Products and Documentation.
collections:
  company:
    output: true
    permalink: /membership/:name/
  core:
    output: true
    permalink: /:collection/:path/
  engineering:
    output: true
    permalink: /:collection/:name/
  projects:
    output: false
    permalink: /engineering/:collection/:path/
  services:
    output: true
    permalink: /:collection/:name/
  authors:
    output: true
    permalink: /author/:name/
  internships:
    output: true
    permalink: /careers/internships/:name/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/social-media-image.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  - scope:
      path: "_posts/events"
    values:
      layout: event-index
      comments: false
      author: linaro
      permalink: /events/:title/
      categories: ["events"]
  - scope:
      path: "_posts/events/resources"
    values:
      layout: resource-post
      comments: false
      author: linaro
      permalink: /events/:title/
      categories: ["event_resources"]
  - scope:
      path: "_posts/awards"
      type: "posts"
    values:
      layout: award-page
      comments: false
  - scope:
      path: ""
      type: "company"
    values:
      layout: company
  - scope:
      path: "_company/archived"
      type: "company"
    values:
      archived: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
  - scope:
      type: "internships"
    values:
      layout: vacancy
  - scope:
      path: ""
      type: "core"
    values:
      layout: work-layout
      image: ""
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project-page
      project: true
      _hide_content: true
  - scope:
      path: ""
      type: "engineering"
    values:
      layout: landing-page
      css-package: landing-page
      js-package: engineering-landing-page
  - scope:
      path: ""
      type: "services"
    values:
      layout: developer-services-layout
      image:
        name: LinaroDSVertical.png
        path: /assets/images/content/LinaroDSVertical.png
  - scope:
      path: "/sitemap.xml"
    values:
      redirect_from: /sitemap/
# Gems that should be included in the Jekyll builld of this site.
plugins:
  - jekyll-seo-tag
  - jekyll-readme-index
  - uglifier
  - jekyll-assets
  - jekyll-tidy
  - jekyll-redirect-from
  - autoprefixer-rails
  - jekyll-paginate-v2
# Compress the html and beau2tify it.
jekyll_tidy: # Compress the html and beautify it.
  compress_html: true
  exclude: [robots.txt] # Exclude the robots.txt file from removal of whitespace
# Jekyll Assets plugin - set js and css to true so it compresses on jekyll build
assets:
  compress:
    js: true
  autoprefixer:
    browsers: ["last 2 versions", "> 5%", "IE 9"]
  sources:
    - assets/js/
    - assets/js/vendor/
    - assets/js/app/
    - assets/images
    - assets/images/members
    - assets/images/people
    - assets/images/content
    - assets/images/blog
    - assets/css/

# Sass configuration - compressed and sass_dir of the root Jekyll assets folder.
sass:
  style: compressed
  load_paths:
    - assets/css
#paginate_path: /:categories/:num/

# Jekyll Pagination V2 Configuration
pagination:
  permalink: "/:num/"
  enabled: true
  per_page: 9
  trail:
    before: 2
    after: 2
  sort_reverse: true
  sort_field: "date"

# Jekyll pagination v2 autopages configuration.
autopages:
  enabled: false

using_assets: true
include: ["_pages"]

# Cloud Cannon Configuration
_options:
  image: # Front matter field
    uploads_dir: "assets/images/featured-images/:title"
  content: # Content Editor and block Editable Regions
    uploads_dir: "assets/images/content/:title"
