name: PullRequestAction

on:
  pull_request_target:
    branches: [ master ]

jobs:
  process-pull-request:
    runs-on: self-hosted
    steps:
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.LINARO_BUILD_KEY }}
          path: website

      - name: Initialise environment
        run: cat "$GITHUB_WORKSPACE/website/.github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - run: env

      - name: Initialise status
        run: /srv/github-action-scripts/init-deploy-preview.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge test branch
        uses: linaro-its/merge-test-branch@v2.6
        with:
          path: website

      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links
        run: /srv/github-action-scripts/check-links.sh

      - name: Check routing rules
        run: /srv/github-action-scripts/test-routing-rules.sh
