name: PullRequestAction

on:
  pull_request_target:
    branches: [ master ]

# Cancel in-progress jobs or runs for the current pull request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  process-pull-request:
    runs-on: self-hosted
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.LINARO_BUILD_KEY }}
          path: website

      - name: Initialise environment
        run: cat "$GITHUB_WORKSPACE/website/.github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - run: env

      - name: Initialise status
        run: /srv/github-action-scripts/init-deploy-preview.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge test branch
        uses: linaro-its/merge-test-branch@v3.0
        with:
          path: website

      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links
        run: >-
          /srv/github-action-scripts/check-links.sh
          --skip-dns-check ${{ github.workspace }}/website/_data/fqdn_exceptions.txt
          --no-external-errors

      - name: Check routing rules
        run: /srv/github-action-scripts/test-routing-rules.sh

      - name: Calculate test site url for a11y scan
        run: |
          PR_NUMBER=$(jq -r ".pull_request.number" $GITHUB_EVENT_PATH)
          BUILDDIR="$AWS_STATIC_SITE_URL-$PR_NUMBER"
          echo "TEST_URL=$BUILDDIR.ghactions.linaro.org" >> $GITHUB_ENV

      - run: env

      # - name: Run Pa11y scan
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: CheckSite
      #     repo: linaro-its/pa11y-ci-container
      #     token: ${{ secrets.BUILD_REPO_TOKEN }}
      #     inputs: '{ "uri": "${{ env.SITE_URL }}" }'
