name: PushAction

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# Cancel in-progress jobs or runs for the current workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  process-push:
    runs-on: self-hosted
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.LINARO_BUILD_KEY }}
          path: website

      - name: Initialise environment
        run: cat "$GITHUB_WORKSPACE/website/.github-env-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - run: env

      - name: Directory push/pop
        uses: linaro-its/directory-push-and-pop@v3.0
        with:
          cacheDirectory: /srv/site-builds
          namedDirectory: ${{ env.SITE_URL }}
          destinationDirectory: ${{ github.workspace }}/website

      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links
        run: >-
          /srv/github-action-scripts/check-links.sh ${{ github.workspace }}/website/${{ env.SITE_URL }}
          --skip-dns-check ${{ github.workspace }}/website/_data/fqdn_exceptions.txt
          --create-github-issue https://api.github.com/repos/Linaro/website/issues
          --assign-github-issue '["EbbaSimpson"]'
          --github-access-token ${{ secrets.GITHUB_TOKEN }}

      - name: Check routing rules
        run: /srv/github-action-scripts/test-routing-rules.sh

      - name: Make staging directory
        run: mkdir -p /srv/s3-staging/${{ env.SITE_URL }}

      - name: Sync build to staging directory
        run: rsync -crui ${{ github.workspace }}/website/${{ env.SITE_URL }}/ /srv/s3-staging/${{ env.SITE_URL }} --delete

      - name: Upload to S3
        run: /srv/github-action-scripts/upload-to-s3-root.sh

      - name: Set up Lambda redirect
        run: /srv/github-action-scripts/set-up-lambda-redirect.sh ${{ github.workspace }}/website/

      - name: Set up security headers
        run: cd /srv/github-action-scripts && pipenv run python lambda-security-headers.py

      - name: Invalidate CloudFront cache
        run: /srv/github-action-scripts/invalidate-cloudfront.sh

      # - name: Run Pa11y scan
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: CheckSite
      #     repo: linaro-its/pa11y-ci-container
      #     token: ${{ secrets.BUILD_REPO_TOKEN }}
      #     inputs: '{ "uri": "${{ env.SITE_URL }}" }'
