name: UpdateMembers

on:
  workflow_dispatch:

jobs:
  confluence:
    runs-on: self-hosted
    steps:
      - name: Rebuild Confluence pages
        run: cd /srv/github-action-scripts && pipenv run python rebuild_confluence_pages.py

  website:
    runs-on: self-hosted
    steps:
      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.LINARO_BUILD_KEY }}
          path: website

      - name: Update website repo
        run: cd /srv/github-action-scripts && pipenv run python update_members.py Linaro
        env:
          TOKEN: ${{ secrets.BUILD_REPO_TOKEN }}

#       - name: Trigger 96Boards update
#         run: >-
#           curl -X POST https://api.github.com/repos/96Boards/website/dispatches
#           -H 'Accept: application/vnd.github.everest-preview+json'
#           -u ${{ secrets.BUILD_REPO_TOKEN }}
#           --data '{"event_type": "UpdateMembers", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
